# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Ivendor/assimp/include -Iinclude -Ivendor -Iopenssl -Ivendor/glfw/include -Ivendor/glad/include -Ivendor/glm -Ivendor/zip/src -Ivendor/imgui -Ivendor/implot -Ivendor/lua -Ivendor/muparser/include -Ivendor/imgui-node-editor
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
	@echo Running postbuild commands
	xcopy "$(SolutionDir)Binaries\Data" "$(TargetDir)Data\" /e /r /y
	xcopy "$(SolutionDir)Binaries\VCRuntime" "$(TargetDir)VCRuntime\" /e /r /y
endef

ifeq ($(config),debug)
TARGETDIR = ../bin/Debug-linux-x86_64
TARGET = $(TARGETDIR)/TerraForge3D
OBJDIR = ../bin/intermediates/Debug-linux-x86_64/TerraForge3D
DEFINES += -DNULL=0 -DTERR3D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -msse4.1
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -msse4.1 -std=c++17
LIBS += ../bin/Debug-linux-x86_64/libTerraForge3DLib.a vendor/glfw/bin/Debug-linux-x86_64/GLFW/libGLFW.a vendor/glad/bin/Debug-linux-x86_64/Glad/libGlad.a vendor/zip/bin/Debug-linux-x86_64/Zip/libZip.a vendor/imgui/bin/Debug-linux-x86_64/ImGui/libImGui.a vendor/imnodes/bin/Debug-linux-x86_64/ImNodes/libImNodes.a vendor/implot/bin/Debug-linux-x86_64/ImPlot/libImPlot.a vendor/imgui-node-editor/bin/Debug-linux-x86_64/ImGuiNodeEditor/libImGuiNodeEditor.a vendor/text-editor/bin/Debug-linux-x86_64/ImColorTextEdit/libImColorTextEdit.a vendor/lua/bin/Debug-linux-x86_64/Lua/libLua.a vendor/muparser/bin/Debug-linux-x86_64/MuParser/libMuParser.a vendor/assimp/bin/Debug-linux-x86_64/libAssimp.a -lGL -lOpenCL -llibssl -llibcrypto -ldl -lpthread
LDDEPS += ../bin/Debug-linux-x86_64/libTerraForge3DLib.a vendor/glfw/bin/Debug-linux-x86_64/GLFW/libGLFW.a vendor/glad/bin/Debug-linux-x86_64/Glad/libGlad.a vendor/zip/bin/Debug-linux-x86_64/Zip/libZip.a vendor/imgui/bin/Debug-linux-x86_64/ImGui/libImGui.a vendor/imnodes/bin/Debug-linux-x86_64/ImNodes/libImNodes.a vendor/implot/bin/Debug-linux-x86_64/ImPlot/libImPlot.a vendor/imgui-node-editor/bin/Debug-linux-x86_64/ImGuiNodeEditor/libImGuiNodeEditor.a vendor/text-editor/bin/Debug-linux-x86_64/ImColorTextEdit/libImColorTextEdit.a vendor/lua/bin/Debug-linux-x86_64/Lua/libLua.a vendor/muparser/bin/Debug-linux-x86_64/MuParser/libMuParser.a vendor/assimp/bin/Debug-linux-x86_64/libAssimp.a
ALL_LDFLAGS += $(LDFLAGS) -L../libs/linux -L/usr/lib64 -m64

else ifeq ($(config),release)
TARGETDIR = ../bin/Release-linux-x86_64
TARGET = $(TARGETDIR)/TerraForge3D
OBJDIR = ../bin/intermediates/Release-linux-x86_64/TerraForge3D
DEFINES += -DNULL=0 -DTERR3D_RELEASE
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -msse4.1 /Qpar /fp:fast
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -msse4.1 -std=c++17 /Qpar /fp:fast
LIBS += ../bin/Release-linux-x86_64/libTerraForge3DLib.a vendor/glfw/bin/Release-linux-x86_64/GLFW/libGLFW.a vendor/glad/bin/Release-linux-x86_64/Glad/libGlad.a vendor/zip/bin/Release-linux-x86_64/Zip/libZip.a vendor/imgui/bin/Release-linux-x86_64/ImGui/libImGui.a vendor/imnodes/bin/Release-linux-x86_64/ImNodes/libImNodes.a vendor/implot/bin/Release-linux-x86_64/ImPlot/libImPlot.a vendor/imgui-node-editor/bin/Release-linux-x86_64/ImGuiNodeEditor/libImGuiNodeEditor.a vendor/text-editor/bin/Release-linux-x86_64/ImColorTextEdit/libImColorTextEdit.a vendor/lua/bin/Release-linux-x86_64/Lua/libLua.a vendor/muparser/bin/Release-linux-x86_64/MuParser/libMuParser.a vendor/assimp/bin/Release-linux-x86_64/libAssimp.a -lGL -lOpenCL -llibssl -llibcrypto -ldl -lpthread
LDDEPS += ../bin/Release-linux-x86_64/libTerraForge3DLib.a vendor/glfw/bin/Release-linux-x86_64/GLFW/libGLFW.a vendor/glad/bin/Release-linux-x86_64/Glad/libGlad.a vendor/zip/bin/Release-linux-x86_64/Zip/libZip.a vendor/imgui/bin/Release-linux-x86_64/ImGui/libImGui.a vendor/imnodes/bin/Release-linux-x86_64/ImNodes/libImNodes.a vendor/implot/bin/Release-linux-x86_64/ImPlot/libImPlot.a vendor/imgui-node-editor/bin/Release-linux-x86_64/ImGuiNodeEditor/libImGuiNodeEditor.a vendor/text-editor/bin/Release-linux-x86_64/ImColorTextEdit/libImColorTextEdit.a vendor/lua/bin/Release-linux-x86_64/Lua/libLua.a vendor/muparser/bin/Release-linux-x86_64/MuParser/libMuParser.a vendor/assimp/bin/Release-linux-x86_64/libAssimp.a
ALL_LDFLAGS += $(LDFLAGS) -L../libs/linux -L/usr/lib64 -m64 -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/EntryPoint.o
GENERATED += $(OBJDIR)/Main.o
OBJECTS += $(OBJDIR)/EntryPoint.o
OBJECTS += $(OBJDIR)/Main.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking TerraForge3D
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning TerraForge3D
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/EntryPoint.o: src/Base/EntryPoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Main.o: src/Main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif