var annotated_dup =
[
    [ "nlohmann", "d3/d9b/namespacenlohmann.html", [
      [ "detail", "dc/df0/namespacenlohmann_1_1detail.html", [
        [ "container_input_adapter_factory_impl", null, [
          [ "container_input_adapter_factory", "d1/d62/structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
          [ "container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "dc/dc8/structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adaptec6d36799bbab06a12576748f72ebcf00.html", null ]
        ] ],
        [ "dtoa_impl", "dc/d41/namespacenlohmann_1_1detail_1_1dtoa__impl.html", [
          [ "boundaries", "dc/d41/namespacenlohmann_1_1detail_1_1dtoa__impl.html#df/ddb/structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries", null ],
          [ "cached_power", "dc/d41/namespacenlohmann_1_1detail_1_1dtoa__impl.html#d5/dfe/structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power", null ],
          [ "diyfp", "d4/d54/structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", "d4/d54/structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp" ]
        ] ],
        [ "utility_internal", null, [
          [ "Extend", "d4/ddf/structnlohmann_1_1detail_1_1utility__internal_1_1_extend.html", null ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "dc/d28/structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_intse4b696320406a0717efa9a961a507d9c.html", null ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "dc/d2c/structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints55b30810c0f772136f5c0a2221b86a09.html", null ],
          [ "Gen", "de/de7/structnlohmann_1_1detail_1_1utility__internal_1_1_gen.html", null ],
          [ "Gen< T, 0 >", "d9/d58/structnlohmann_1_1detail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4.html", null ]
        ] ],
        [ "binary_reader", "d6/d30/classnlohmann_1_1detail_1_1binary__reader.html", "d6/d30/classnlohmann_1_1detail_1_1binary__reader" ],
        [ "binary_writer", "df/d1a/classnlohmann_1_1detail_1_1binary__writer.html", "df/d1a/classnlohmann_1_1detail_1_1binary__writer" ],
        [ "conjunction", "dd/dde/structnlohmann_1_1detail_1_1conjunction.html", null ],
        [ "conjunction< B1 >", "dd/d0d/structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ],
        [ "conjunction< B1, Bn... >", "df/d9c/structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ],
        [ "detector", "dc/df0/namespacenlohmann_1_1detail.html#dd/d10/structnlohmann_1_1detail_1_1detector", null ],
        [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "dc/df0/namespacenlohmann_1_1detail.html#d8/dea/structnlohmann_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4", null ],
        [ "exception", "de/df2/classnlohmann_1_1detail_1_1exception.html", "de/df2/classnlohmann_1_1detail_1_1exception" ],
        [ "external_constructor", "dc/df0/namespacenlohmann_1_1detail.html#d2/df4/structnlohmann_1_1detail_1_1external__constructor", null ],
        [ "external_constructor< value_t::array >", "d4/d91/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
        [ "external_constructor< value_t::binary >", "d3/d09/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
        [ "external_constructor< value_t::boolean >", "d5/d36/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
        [ "external_constructor< value_t::number_float >", "d8/dff/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
        [ "external_constructor< value_t::number_integer >", "dc/dd7/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
        [ "external_constructor< value_t::number_unsigned >", "d5/df9/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
        [ "external_constructor< value_t::object >", "d7/d38/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
        [ "external_constructor< value_t::string >", "da/dac/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
        [ "file_input_adapter", "da/d14/classnlohmann_1_1detail_1_1file__input__adapter.html", "da/d14/classnlohmann_1_1detail_1_1file__input__adapter" ],
        [ "from_json_fn", "d5/d4d/structnlohmann_1_1detail_1_1from__json__fn.html", null ],
        [ "has_from_json", "dc/dac/structnlohmann_1_1detail_1_1has__from__json.html", null ],
        [ "has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "d4/d20/structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896.html", null ],
        [ "has_non_default_from_json", "d7/d08/structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
        [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "df/d92/structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8.html", null ],
        [ "has_to_json", "d9/d6c/structnlohmann_1_1detail_1_1has__to__json.html", null ],
        [ "has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "d6/da9/structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77.html", null ],
        [ "identity_tag", "dc/df0/namespacenlohmann_1_1detail.html#d0/db1/structnlohmann_1_1detail_1_1identity__tag", null ],
        [ "input_stream_adapter", "db/df0/classnlohmann_1_1detail_1_1input__stream__adapter.html", "db/df0/classnlohmann_1_1detail_1_1input__stream__adapter" ],
        [ "integer_sequence", "d9/d1c/structnlohmann_1_1detail_1_1integer__sequence.html", null ],
        [ "internal_iterator", "dc/df0/namespacenlohmann_1_1detail.html#d7/d10/structnlohmann_1_1detail_1_1internal__iterator", "dc/df0/namespacenlohmann_1_1detail_d7/d10/structnlohmann_1_1detail_1_1internal__iterator_dup" ],
        [ "invalid_iterator", "d4/d5f/classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "is_basic_json", "d4/df6/structnlohmann_1_1detail_1_1is__basic__json.html", null ],
        [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "d1/d1d/structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
        [ "is_compatible_array_type", "d8/d94/structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
        [ "is_compatible_array_type_impl", "dc/d4b/structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
        [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value &&is_detected< iterator_t, CompatibleArrayType >::value &&!is_iterator_traits< iterator_traits< CompatibleArrayType > >::value > >", "d2/d01/structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compati48bb30a3298fd067e7b3dce036e40849.html", null ],
        [ "is_compatible_integer_type", "d1/d21/structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
        [ "is_compatible_integer_type_impl", "dd/d13/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
        [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "dc/d7f/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604.html", null ],
        [ "is_compatible_object_type", "d5/dda/structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
        [ "is_compatible_object_type_impl", "dc/da5/structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
        [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "d7/d4b/structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5.html", null ],
        [ "is_compatible_string_type", "db/d4e/structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
        [ "is_compatible_string_type_impl", "d2/d3a/structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", null ],
        [ "is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >", "db/d96/structnlohmann_1_1detail_1_1is__compatible__string__type__impl_3_01_basic_json_type_00_01_compat6590904cab40fc73f430e4c7518179a2.html", null ],
        [ "is_compatible_type", "d3/d71/structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
        [ "is_compatible_type_impl", "d9/d66/structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
        [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "d1/d50/structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_typ632bee7ec037fc0233f1bbe9dd7d8874.html", null ],
        [ "is_complete_type", "d2/db3/structnlohmann_1_1detail_1_1is__complete__type.html", null ],
        [ "is_complete_type< T, decltype(void(sizeof(T)))>", "dc/d2b/structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
        [ "is_constructible", "d7/d10/structnlohmann_1_1detail_1_1is__constructible.html", null ],
        [ "is_constructible< const std::pair< T1, T2 > >", "d9/db0/structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_constructible< const std::tuple< Ts... > >", "d5/d98/structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible< std::pair< T1, T2 > >", "d5/dd0/structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_constructible< std::tuple< Ts... > >", "dc/d2e/structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible_array_type", "d3/d52/structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
        [ "is_constructible_array_type_impl", "d8/d8b/structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value) &&is_detected< value_type_t, ConstructibleArrayType >::value &&is_detected< iterator_t, ConstructibleArrayType >::value &&is_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >", "d1/d83/structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_consc1d990207880ce90fa6000c550fffe97.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "d8/d15/structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
        [ "is_constructible_object_type", "dc/d11/structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
        [ "is_constructible_object_type_impl", "dd/da4/structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
        [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "d3/ddf/structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545.html", null ],
        [ "is_constructible_string_type", "d3/d84/structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ],
        [ "is_constructible_string_type_impl", "de/df0/structnlohmann_1_1detail_1_1is__constructible__string__type__impl.html", null ],
        [ "is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >", "d7/d4d/structnlohmann_1_1detail_1_1is__constructible__string__type__impl_3_01_basic_json_type_00_01_con83e8ebfe9593f851a60fdb8360df1512.html", null ],
        [ "is_constructible_tuple", "df/d17/structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
        [ "is_constructible_tuple< T1, std::tuple< Args... > >", "d7/d82/structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible", "d2/d91/structnlohmann_1_1detail_1_1is__default__constructible.html", null ],
        [ "is_default_constructible< const std::pair< T1, T2 > >", "d6/d02/structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_default_constructible< const std::tuple< Ts... > >", "df/d31/structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible< std::pair< T1, T2 > >", "de/dd7/structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_default_constructible< std::tuple< Ts... > >", "dd/d1b/structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_detected_lazy", "d6/d8c/structnlohmann_1_1detail_1_1is__detected__lazy.html", null ],
        [ "is_getable", "de/dbc/structnlohmann_1_1detail_1_1is__getable.html", null ],
        [ "is_iterator_of_multibyte", "d6/d46/structnlohmann_1_1detail_1_1is__iterator__of__multibyte.html", null ],
        [ "is_iterator_traits", "d3/d30/structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
        [ "is_iterator_traits< iterator_traits< T > >", "d1/d1f/structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01_t_01_4_01_4.html", null ],
        [ "is_json_ref", "d3/d0b/structnlohmann_1_1detail_1_1is__json__ref.html", null ],
        [ "is_json_ref< json_ref< T > >", "d1/db6/structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
        [ "is_ordered_map", "de/d3b/structnlohmann_1_1detail_1_1is__ordered__map.html", "de/d3b/structnlohmann_1_1detail_1_1is__ordered__map" ],
        [ "is_sax", "dc/dc3/structnlohmann_1_1detail_1_1is__sax.html", null ],
        [ "is_sax_static_asserts", "d1/d2d/structnlohmann_1_1detail_1_1is__sax__static__asserts.html", null ],
        [ "iter_impl", "d1/d7c/classnlohmann_1_1detail_1_1iter__impl.html", "d1/d7c/classnlohmann_1_1detail_1_1iter__impl" ],
        [ "iteration_proxy", "db/dda/classnlohmann_1_1detail_1_1iteration__proxy.html", "db/dda/classnlohmann_1_1detail_1_1iteration__proxy" ],
        [ "iteration_proxy_value", "d5/de9/classnlohmann_1_1detail_1_1iteration__proxy__value.html", "d5/de9/classnlohmann_1_1detail_1_1iteration__proxy__value" ],
        [ "iterator_input_adapter", "d4/dbe/classnlohmann_1_1detail_1_1iterator__input__adapter.html", null ],
        [ "iterator_input_adapter_factory", "d4/d8c/structnlohmann_1_1detail_1_1iterator__input__adapter__factory.html", null ],
        [ "iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "d6/d9f/structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__ifdbe9caa11c2ca51101ba1bbd1184c22c.html", null ],
        [ "iterator_traits", "dc/df0/namespacenlohmann_1_1detail.html#d8/db6/structnlohmann_1_1detail_1_1iterator__traits", null ],
        [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "dc/df0/namespacenlohmann_1_1detail.html#dc/dc1/structnlohmann_1_1detail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__objec8d960665487688165530972cda4f1bea", null ],
        [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "dc/df9/structnlohmann_1_1detail_1_1iterator__traits_3_01_t_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01_t_01_4_1_1value_01_4_01_4.html", null ],
        [ "iterator_types", "dc/df0/namespacenlohmann_1_1detail.html#d5/d3c/structnlohmann_1_1detail_1_1iterator__types", null ],
        [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "dc/df0/namespacenlohmann_1_1detail.html#db/da7/structnlohmann_1_1detail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1differenc4a413e9bd546446175f10f15c5631361", null ],
        [ "json_ref", "da/d10/classnlohmann_1_1detail_1_1json__ref.html", null ],
        [ "json_reverse_iterator", "de/d74/classnlohmann_1_1detail_1_1json__reverse__iterator.html", "de/d74/classnlohmann_1_1detail_1_1json__reverse__iterator" ],
        [ "json_sax_acceptor", "d2/d2a/classnlohmann_1_1detail_1_1json__sax__acceptor.html", null ],
        [ "json_sax_dom_callback_parser", "d6/d69/classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", "d6/d69/classnlohmann_1_1detail_1_1json__sax__dom__callback__parser" ],
        [ "json_sax_dom_parser", "dc/d68/classnlohmann_1_1detail_1_1json__sax__dom__parser.html", "dc/d68/classnlohmann_1_1detail_1_1json__sax__dom__parser" ],
        [ "lexer", "d8/d22/classnlohmann_1_1detail_1_1lexer.html", "d8/d22/classnlohmann_1_1detail_1_1lexer" ],
        [ "lexer_base", "de/d77/classnlohmann_1_1detail_1_1lexer__base.html", "de/d77/classnlohmann_1_1detail_1_1lexer__base" ],
        [ "make_void", "dc/df0/namespacenlohmann_1_1detail.html#d3/d72/structnlohmann_1_1detail_1_1make__void", null ],
        [ "negation", "d1/d91/structnlohmann_1_1detail_1_1negation.html", null ],
        [ "nonesuch", "da/d31/structnlohmann_1_1detail_1_1nonesuch.html", null ],
        [ "other_error", "d5/d1b/classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "out_of_range", "d2/d67/classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "output_adapter", "df/d13/classnlohmann_1_1detail_1_1output__adapter.html", null ],
        [ "output_adapter_protocol", "dc/d9b/structnlohmann_1_1detail_1_1output__adapter__protocol.html", null ],
        [ "output_stream_adapter", "d8/d94/classnlohmann_1_1detail_1_1output__stream__adapter.html", null ],
        [ "output_string_adapter", "d2/d39/classnlohmann_1_1detail_1_1output__string__adapter.html", null ],
        [ "output_vector_adapter", "d5/d66/classnlohmann_1_1detail_1_1output__vector__adapter.html", null ],
        [ "parse_error", "d5/d1a/classnlohmann_1_1detail_1_1parse__error.html", "d5/d1a/classnlohmann_1_1detail_1_1parse__error" ],
        [ "parser", "df/d6b/classnlohmann_1_1detail_1_1parser.html", "df/d6b/classnlohmann_1_1detail_1_1parser" ],
        [ "position_t", "d6/d02/structnlohmann_1_1detail_1_1position__t.html", "d6/d02/structnlohmann_1_1detail_1_1position__t" ],
        [ "primitive_iterator_t", "d2/d2c/classnlohmann_1_1detail_1_1primitive__iterator__t.html", "d2/d2c/classnlohmann_1_1detail_1_1primitive__iterator__t" ],
        [ "priority_tag", "dc/df0/namespacenlohmann_1_1detail.html#d7/d78/structnlohmann_1_1detail_1_1priority__tag", null ],
        [ "priority_tag< 0 >", "dc/df0/namespacenlohmann_1_1detail.html#d2/ddd/structnlohmann_1_1detail_1_1priority__tag_3_010_01_4", null ],
        [ "serializer", "d4/d0a/classnlohmann_1_1detail_1_1serializer.html", "d4/d0a/classnlohmann_1_1detail_1_1serializer" ],
        [ "span_input_adapter", "da/d7e/classnlohmann_1_1detail_1_1span__input__adapter.html", null ],
        [ "static_const", "d1/d9b/structnlohmann_1_1detail_1_1static__const.html", null ],
        [ "to_json_fn", "d2/d7e/structnlohmann_1_1detail_1_1to__json__fn.html", null ],
        [ "type_error", "da/d1c/classnlohmann_1_1detail_1_1type__error.html", null ],
        [ "wide_string_input_adapter", "d1/dea/classnlohmann_1_1detail_1_1wide__string__input__adapter.html", "d1/dea/classnlohmann_1_1detail_1_1wide__string__input__adapter" ],
        [ "wide_string_input_helper", "dc/df0/namespacenlohmann_1_1detail.html#d2/d2c/structnlohmann_1_1detail_1_1wide__string__input__helper", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 2 >", "d4/d51/structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_012_01_4.html", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 4 >", "da/db6/structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_014_01_4.html", null ]
      ] ],
      [ "adl_serializer", "dc/dc7/structnlohmann_1_1adl__serializer.html", "dc/dc7/structnlohmann_1_1adl__serializer" ],
      [ "basic_json", "d9/dcc/classnlohmann_1_1basic__json.html", "d9/dcc/classnlohmann_1_1basic__json" ],
      [ "byte_container_with_subtype", "dd/d0d/classnlohmann_1_1byte__container__with__subtype.html", "dd/d0d/classnlohmann_1_1byte__container__with__subtype" ],
      [ "json_pointer", "da/de8/classnlohmann_1_1json__pointer.html", "da/de8/classnlohmann_1_1json__pointer" ],
      [ "json_sax", "d0/d82/structnlohmann_1_1json__sax.html", "d0/d82/structnlohmann_1_1json__sax" ],
      [ "ordered_map", "d6/da7/structnlohmann_1_1ordered__map.html", null ]
    ] ],
    [ "std", "d8/dcc/namespacestd.html", [
      [ "hash< nlohmann::json >", "dd/d6b/structstd_1_1hash_3_01nlohmann_1_1json_01_4.html", "dd/d6b/structstd_1_1hash_3_01nlohmann_1_1json_01_4" ],
      [ "less<::nlohmann::detail::value_t >", "df/d4e/structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4.html", "df/d4e/structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4" ],
      [ "tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "d8/dcc/namespacestd.html#d4/dfa/classstd_1_1tuple__element_3_01_n_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4", null ],
      [ "tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "db/d81/classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", null ]
    ] ],
    [ "AbsNode", "d4/d5d/class_abs_node.html", null ],
    [ "AddNode", "dc/d48/class_add_node.html", null ],
    [ "AdvancedErosionFilter", "d5/deb/class_advanced_erosion_filter.html", null ],
    [ "Application", "de/d6b/class_application.html", null ],
    [ "ApplicationState", "da/d59/struct_application_state.html", null ],
    [ "ApplicationStateCameras", "df/d5e/struct_application_state_cameras.html", null ],
    [ "ApplicationStateConstants", "d7/dee/struct_application_state_constants.html", null ],
    [ "ApplicationStateFrameBuffers", "da/d16/struct_application_state_frame_buffers.html", null ],
    [ "ApplicationStateGlobals", "d2/d98/struct_application_state_globals.html", null ],
    [ "ApplicationStateModels", "d5/d75/struct_application_state_models.html", null ],
    [ "ApplicationStateModules", "d8/d67/struct_application_state_modules.html", null ],
    [ "ApplicationStateShaders", "d4/d38/struct_application_state_shaders.html", null ],
    [ "ApplicationStateStates", "d6/d20/struct_application_state_states.html", null ],
    [ "ApplicationStateStatistics", "db/dbd/struct_application_state_statistics.html", null ],
    [ "ApplicationStateTextures", "d0/da1/struct_application_state_textures.html", null ],
    [ "ApplicationStateWindows", "da/dcc/struct_application_state_windows.html", null ],
    [ "BakeToSlotNode", "d0/d78/class_bake_to_slot_node.html", null ],
    [ "BlendNode", "d7/d14/class_blend_node.html", null ],
    [ "Camera", "da/dbb/class_camera.html", null ],
    [ "ClampNode", "da/d1c/class_clamp_node.html", null ],
    [ "ClearColor", "da/de2/struct_clear_color.html", null ],
    [ "ClearMeshGenerator", "d5/dc8/class_clear_mesh_generator.html", null ],
    [ "ComputeKernel", "d3/daa/class_compute_kernel.html", null ],
    [ "ComputeShader", "d0/d73/class_compute_shader.html", null ],
    [ "CosNode", "d7/d47/class_cos_node.html", null ],
    [ "CPUNodeEditor", "d5/dcc/class_c_p_u_node_editor.html", null ],
    [ "CPUNoiseLayersGenerator", "d8/d4a/class_c_p_u_noise_layers_generator.html", null ],
    [ "CubeMapManager", "da/d98/class_cube_map_manager.html", null ],
    [ "CurveNode", "dd/d5b/class_curve_node.html", null ],
    [ "CustomShaderNode", "db/da0/class_custom_shader_node.html", null ],
    [ "DefaultCustomNode", "d3/d89/struct_default_custom_node.html", null ],
    [ "DivNode", "de/d68/class_div_node.html", null ],
    [ "DrawFilter", "d5/dd6/class_draw_filter.html", null ],
    [ "DummyNode", "d2/d31/class_dummy_node.html", null ],
    [ "DuplicateNode", "dd/d21/class_duplicate_node.html", null ],
    [ "ErosionFilter", "d3/d96/class_erosion_filter.html", null ],
    [ "Filter", "d2/d70/class_filter.html", null ],
    [ "FiltersManager", "da/d39/class_filters_manager.html", null ],
    [ "Float3Node", "d9/d1c/class_float3_node.html", null ],
    [ "FloatNode", "d5/dc7/class_float_node.html", null ],
    [ "FoliageItem", "d2/de8/struct_foliage_item.html", null ],
    [ "FoliageManager", "d5/da2/class_foliage_manager.html", null ],
    [ "FrameBuffer", "d8/d23/class_frame_buffer.html", null ],
    [ "GeneratorMask", "da/d74/struct_generator_mask.html", null ],
    [ "GeneratorMaskManager", "d6/d68/class_generator_mask_manager.html", null ],
    [ "GitHubData", "dd/d8c/struct_git_hub_data.html", null ],
    [ "GLSLFunction", "db/d01/struct_g_l_s_l_function.html", null ],
    [ "GLSLHandler", "d9/dab/class_g_l_s_l_handler.html", null ],
    [ "GLSLLine", "da/d76/struct_g_l_s_l_line.html", null ],
    [ "GLSLMacro", "df/df1/struct_g_l_s_l_macro.html", null ],
    [ "GLSLSSBO", "d5/ddc/struct_g_l_s_l_s_s_b_o.html", null ],
    [ "GLSLUniform", "dd/d69/struct_g_l_s_l_uniform.html", null ],
    [ "GPUErosionFilter", "d4/dc6/class_g_p_u_erosion_filter.html", null ],
    [ "GPUNoiseLayer", "df/d26/struct_g_p_u_noise_layer.html", null ],
    [ "GPUNoiseLayerGenerator", "da/ded/class_g_p_u_noise_layer_generator.html", null ],
    [ "Hash", "d2/d7a/struct_hash.html", null ],
    [ "HeightAndGradient", "d8/df5/struct_height_and_gradient.html", null ],
    [ "Heightmap", "dc/dcb/class_heightmap.html", null ],
    [ "HeightmapNode", "d0/d84/class_heightmap_node.html", null ],
    [ "HillNode", "d5/d15/class_hill_node.html", null ],
    [ "IVec2", "dc/d6f/struct_i_vec2.html", null ],
    [ "LayeredNoiseManager", "d8/d05/class_layered_noise_manager.html", null ],
    [ "LightManager", "d1/d3e/class_light_manager.html", null ],
    [ "Logger", "d3/d42/class_logger.html", null ],
    [ "LoggingOutputStreambuf", "da/d90/class_logging_output_streambuf.html", null ],
    [ "MainMenu", "d4/d04/class_main_menu.html", null ],
    [ "MathFunctionNode", "d5/dd4/class_math_function_node.html", null ],
    [ "MaxMeshCoordinatesNode", "dd/dc8/class_max_mesh_coordinates_node.html", null ],
    [ "Mesh", "dc/dbe/class_mesh.html", null ],
    [ "MeshCoordinatesNode", "de/d0b/class_mesh_coordinates_node.html", null ],
    [ "MeshGeneratorManager", "d9/db1/class_mesh_generator_manager.html", null ],
    [ "MinMeshCoordinatesNode", "dc/db6/class_min_mesh_coordinates_node.html", null ],
    [ "MinValNode", "d2/d46/class_min_val_node.html", null ],
    [ "Model", "d0/de3/class_model.html", null ],
    [ "Module", "dd/df9/class_module.html", "dd/df9/class_module" ],
    [ "ModuleInfo", "d2/db2/struct_module_info.html", "d2/db2/struct_module_info" ],
    [ "ModuleManager", "d8/d79/class_module_manager.html", null ],
    [ "MulNode", "d6/def/class_mul_node.html", null ],
    [ "MyApp", "dd/da7/class_my_app.html", null ],
    [ "NodeEditor", "db/d54/class_node_editor.html", null ],
    [ "NodeEditorConfig", "d2/d48/struct_node_editor_config.html", null ],
    [ "NodeEditorLink", "db/db1/class_node_editor_link.html", null ],
    [ "NodeEditorNode", "da/d6c/class_node_editor_node.html", null ],
    [ "NodeEditorPin", "d2/d45/class_node_editor_pin.html", null ],
    [ "NodeInputParam", "d5/dd0/struct_node_input_param.html", null ],
    [ "NodeOutput", "d6/d3b/struct_node_output.html", null ],
    [ "NoiseCellularNode", "d7/d56/class_noise_cellular_node.html", null ],
    [ "NoiseLayer", "d7/dc4/class_noise_layer.html", null ],
    [ "NoiseLayerInput", "da/d1c/struct_noise_layer_input.html", null ],
    [ "NoiseOpenSimplex2Node", "da/db8/class_noise_open_simplex2_node.html", null ],
    [ "NoiseOpenSimplex2SNode", "d9/d3a/class_noise_open_simplex2_s_node.html", null ],
    [ "NoisePerlinNode", "de/dda/class_noise_perlin_node.html", null ],
    [ "NoiseValueCubicNode", "d7/dfa/class_noise_value_cubic_node.html", null ],
    [ "NoiseValueNode", "d1/d32/class_noise_value_node.html", null ],
    [ "OpenCLBuffer", "d6/da2/struct_open_c_l_buffer.html", null ],
    [ "OSLiscences", "da/dfe/class_o_s_liscences.html", null ],
    [ "OutputNode", "df/df6/class_output_node.html", null ],
    [ "PBRMaterialNode", "d3/da4/class_p_b_r_material_node.html", null ],
    [ "PixelateNode", "dc/d9e/class_pixelate_node.html", null ],
    [ "ProjectManager", "d7/d93/class_project_manager.html", null ],
    [ "RandomNumberNode", "dc/d4b/class_random_number_node.html", null ],
    [ "SeaManager", "d3/dac/class_sea_manager.html", null ],
    [ "Serializer", "d0/dc2/class_serializer.html", null ],
    [ "Shader", "d1/d51/class_shader.html", null ],
    [ "ShaderOutputNode", "d1/db6/class_shader_output_node.html", null ],
    [ "ShaderStorageBuffer", "d4/dc3/class_shader_storage_buffer.html", null ],
    [ "ShaderTextureManager", "d4/da6/class_shader_texture_manager.html", null ],
    [ "ShaderTextureNode", "d0/d32/class_shader_texture_node.html", null ],
    [ "ShadingManager", "de/d7d/class_shading_manager.html", null ],
    [ "SharedDataRep", "d5/d6b/struct_shared_data_rep.html", null ],
    [ "SharedMemoryItem", "df/d81/struct_shared_memory_item.html", null ],
    [ "SharedMemoryManager", "d9/d9f/class_shared_memory_manager.html", null ],
    [ "SinNode", "db/dba/class_sin_node.html", null ],
    [ "SkyManager", "db/d15/class_sky_manager.html", null ],
    [ "SNENode", "df/d7c/class_s_n_e_node.html", null ],
    [ "SNEPin", "d8/d44/class_s_n_e_pin.html", null ],
    [ "SquareNode", "d8/de1/class_square_node.html", null ],
    [ "SubNode", "d4/da1/class_sub_node.html", null ],
    [ "SupportersTribute", "db/d47/class_supporters_tribute.html", null ],
    [ "TanNode", "d0/d84/class_tan_node.html", null ],
    [ "Texture2D", "de/dd0/class_texture2_d.html", null ],
    [ "TextureBaker", "d3/d2a/class_texture_baker.html", null ],
    [ "TextureCoordinatesNode", "de/d4e/class_texture_coordinates_node.html", null ],
    [ "TextureCubemap", "d7/df9/class_texture_cubemap.html", null ],
    [ "TextureNode", "dd/d68/class_texture_node.html", null ],
    [ "TextureStore", "d0/d8a/class_texture_store.html", null ],
    [ "TextureStoreItem", "d8/d09/struct_texture_store_item.html", null ],
    [ "TimeBasedSeedNode", "d5/d1f/class_time_based_seed_node.html", null ],
    [ "Vert", "d1/dea/struct_vert.html", null ],
    [ "VisualizerNode", "df/d97/class_visualizer_node.html", null ],
    [ "WindErosionParticle", "d6/dfa/struct_wind_erosion_particle.html", null ],
    [ "Window", "d9/dbf/class_window.html", null ]
];